services:
  airflow-webserver:
    image: apache/airflow:2.6.3
    container_name: airflow_webserver
    restart: unless-stopped
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - SQLALCHEMY_WARN_20=0
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - //c/Users/damian/Documents/IU Digital/Proyecto Integrado 4/proyecto_integrador:/opt/airflow/proyecto_integrador
      - sqlite_db:/opt/airflow
    ports:
      - "8080:8080"
    command: >
      bash -c "
        sleep 10;
        airflow db init;
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true;
        airflow webserver
      "

  airflow-scheduler:
    image: apache/airflow:2.6.3
    container_name: airflow_scheduler
    restart: unless-stopped
    depends_on:
      - airflow-webserver
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - SQLALCHEMY_WARN_20=0
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - //c/Users/damian/Documents/IU Digital/Proyecto Integrado 4/proyecto_integrador:/opt/airflow/proyecto_integrador
      - sqlite_db:/opt/airflow
    command: >
      bash -c "
        while ! airflow db check; do
          echo 'Waiting for DB...';
          sleep 5;
        done;
        airflow scheduler
      "

volumes:
  sqlite_db:
